name: Lint and Deploy
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    lint:
        name: "Lint and Deploy"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node 12
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - run: npm i
              name: Install dependencies
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BRANCH: gh-pages 
                FOLDER: build